In [2]:
import pandas as pd

In [7]:
url = "movies.csv"
df = pd.read_csv(url)
df.head()

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score
0,3f297cf0-2e9d-31c0-b566-6676dd8548b2,Titanic,1997,https://www.rottentomatoes.com/m/titanic,1,88%,69%
1,ed95f56a-dc82-3197-97fd-763ab02d032a,Contagion,2011,https://www.rottentomatoes.com/m/contagion_2011,2,85%,63%
2,f639ff01-58ec-3847-95a0-c1b1b8de5550,Deepwater Horizon,2016,https://www.rottentomatoes.com/m/deepwater_hor...,3,82%,82%
3,7712badd-e5ec-3d28-8787-7fd6301f5a0a,The Wave,2015,https://www.rottentomatoes.com/m/the_wave_2016,4,83%,66%
4,65abd2ca-6095-3acc-b072-00443c4c1fb5,The Impossible,2012,https://www.rottentomatoes.com/m/the_impossibl...,5,82%,84%

In [6]:
best = df.query("movieYear > 2000 and critic_score > '80%'")
best

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score
1,ed95f56a-dc82-3197-97fd-763ab02d032a,Contagion,2011,https://www.rottentomatoes.com/m/contagion_2011,2,85%,63%
2,f639ff01-58ec-3847-95a0-c1b1b8de5550,Deepwater Horizon,2016,https://www.rottentomatoes.com/m/deepwater_hor...,3,82%,82%
3,7712badd-e5ec-3d28-8787-7fd6301f5a0a,The Wave,2015,https://www.rottentomatoes.com/m/the_wave_2016,4,83%,66%
4,65abd2ca-6095-3acc-b072-00443c4c1fb5,The Impossible,2012,https://www.rottentomatoes.com/m/the_impossibl...,5,82%,84%
5,5cf3dfaa-1396-3c86-85ec-3173cad39f22,Black Sea,2014,https://www.rottentomatoes.com/m/black_sea,6,81%,58%