In [1]:
import pandas as pd

In [2]:
url = "synthetic_dataset.csv"
df_2 = pd.read_csv(url)
df_2

     Category   Price    Rating         Stock  Discount
0         NaN  5548.0  1.870322           NaN       0.0
1         NaN  3045.0  4.757798           NaN      38.0
2         NaN  4004.0       NaN      In Stock       0.0
3         NaN  4808.0  1.492085           NaN      33.0
4         NaN  1817.0       NaN  Out of Stock      23.0
...       ...     ...       ...           ...       ...
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

[4362 rows x 5 columns]

In [3]:
df = df_2.iloc[0:11]
df

   Category   Price    Rating         Stock  Discount
0       NaN  5548.0  1.870322           NaN       0.0
1       NaN  3045.0  4.757798           NaN      38.0
2       NaN  4004.0       NaN      In Stock       0.0
3       NaN  4808.0  1.492085           NaN      33.0
4       NaN  1817.0       NaN  Out of Stock      23.0
5       NaN  3522.0       NaN           NaN       NaN
6         C   667.0  3.668341      In Stock      41.0
7         A  7125.0  4.983998  Out of Stock       7.0
8         A  2777.0  2.678384      In Stock       6.0
9       NaN   463.0  4.626187           NaN       3.0
10        A  1151.0  2.947838           NaN       NaN

In [8]:
rows = df.isnull().sum(axis=1)# used to give missing value in rows
column = df.isnull().sum()# used to give missing value in column

In [9]:
column

Category    7
Price       0
Rating      3
Stock       6
Discount    2
dtype: int64

In [10]:
df.isnull()

    Category  Price  Rating  Stock  Discount
0       True  False   False   True     False
1       True  False   False   True     False
2       True  False    True  False     False
3       True  False   False   True     False
4       True  False    True  False     False
5       True  False    True   True      True
6      False  False   False  False     False
7      False  False   False  False     False
8      False  False   False  False     False
9       True  False   False   True     False
10     False  False   False   True      True

In [12]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [18]:
df.fillna(df["Discount"].mean())

     Category   Price     Rating         Stock   Discount
0   16.777778  5548.0   1.870322     16.777778   0.000000
1   16.777778  3045.0   4.757798     16.777778  38.000000
2   16.777778  4004.0  16.777778      In Stock   0.000000
3   16.777778  4808.0   1.492085     16.777778  33.000000
4   16.777778  1817.0  16.777778  Out of Stock  23.000000
5   16.777778  3522.0  16.777778     16.777778  16.777778
6           C   667.0   3.668341      In Stock  41.000000
7           A  7125.0   4.983998  Out of Stock   7.000000
8           A  2777.0   2.678384      In Stock   6.000000
9   16.777778   463.0   4.626187     16.777778   3.000000
10          A  1151.0   2.947838     16.777778  16.777778

In [21]:
Price = df["Price"].astype(int)
Price

0     5548
1     3045
2     4004
3     4808
4     1817
5     3522
6      667
7     7125
8     2777
9      463
10    1151
Name: Price, dtype: int64

In [22]:
frontfill = df.ffill()
frontfill

   Category   Price    Rating         Stock  Discount
0       NaN  5548.0  1.870322           NaN       0.0
1       NaN  3045.0  4.757798           NaN      38.0
2       NaN  4004.0  4.757798      In Stock       0.0
3       NaN  4808.0  1.492085      In Stock      33.0
4       NaN  1817.0  1.492085  Out of Stock      23.0
5       NaN  3522.0  1.492085  Out of Stock      23.0
6         C   667.0  3.668341      In Stock      41.0
7         A  7125.0  4.983998  Out of Stock       7.0
8         A  2777.0  2.678384      In Stock       6.0
9         A   463.0  4.626187      In Stock       3.0
10        A  1151.0  2.947838      In Stock       3.0

In [24]:
frontfill.drop_duplicates(subset=["Rating"])

   Category   Price    Rating         Stock  Discount
0       NaN  5548.0  1.870322           NaN       0.0
1       NaN  3045.0  4.757798           NaN      38.0
3       NaN  4808.0  1.492085      In Stock      33.0
6         C   667.0  3.668341      In Stock      41.0
7         A  7125.0  4.983998  Out of Stock       7.0
8         A  2777.0  2.678384      In Stock       6.0
9         A   463.0  4.626187      In Stock       3.0
10        A  1151.0  2.947838      In Stock       3.0