In [10]:
import pandas as pd

In [15]:
data = {
    "Name": ["Alice","Bob","Harry","Ujjwal"],
    "Maths": [90,84,73,89],
    "Science": [90, 82, 89,98],
    "English": [88, 85, 94,76]
}
df = pd.DataFrame(data)
df

     Name  Maths  Science  English
0   Alice     90       90       88
1     Bob     84       82       85
2   Harry     73       89       94
3  Ujjwal     89       98       76

In [19]:
df_2 = df.melt(id_vars=["Name"],value_vars=["Maths","Science","English"],var_name="Subject",value_name="Marks")
df_2

      Name  Subject  Marks
0    Alice    Maths     90
1      Bob    Maths     84
2    Harry    Maths     73
3   Ujjwal    Maths     89
4    Alice  Science     90
5      Bob  Science     82
6    Harry  Science     89
7   Ujjwal  Science     98
8    Alice  English     88
9      Bob  English     85
10   Harry  English     94
11  Ujjwal  English     76

In [25]:
df_2.to_csv("Pivot.csv" , index=False) # used to create a new csv