In [2]:
import pandas as pd

In [7]:
csv = "Melt.csv"

In [8]:
df = pd.read_csv(csv)

In [9]:
df

      Name  Subject  Marks
0    Alice    Maths     90
1      Bob    Maths     84
2    Harry    Maths     73
3   Ujjwal    Maths     89
4    Alice  Science     90
5      Bob  Science     82
6    Harry  Science     89
7   Ujjwal  Science     98
8    Alice  English     88
9      Bob  English     85
10   Harry  English     94
11  Ujjwal  English     76

In [10]:
# Melt to Pivot

In [16]:
df_2 = df.pivot(index="Subject", columns="Name", values="Marks")
df_2

Name     Alice  Bob  Harry  Ujjwal
Subject
English     88   85     94      76
Maths       90   84     73      89
Science     90   82     89      98